import type { Metadata } from 'next';
import './globals.css';
import { Toaster } from 'sonner';
import { AuthProvider } from '@/app/providers/AuthContext';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-funnel-display">
        <AuthProvider>{children}</AuthProvider>
        <Toaster richColors={true} position="top-right" />
      </body>
    </html>
  );
}
